# Generated by Django 3.0.5 on 2020-08-12 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlCars', '0002_auto_20200809_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='terminado',
            field=models.BooleanField(default=False),
        ),
    ]
