# Generated by Django 3.0.5 on 2020-08-12 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlCars', '0003_alquiler_terminado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='terminado',
            field=models.BooleanField(default=True),
        ),
    ]
