# Generated by Django 3.0.5 on 2020-08-15 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ControlCars', '0005_usuarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='cedula',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='img_perfil',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='telefono',
        ),
    ]
